### ISSUE TITLE
Unused files in TEB

### ISSUE THREAD

**Issue by dmey** [TEB-model/teb#26]
@VakankGrang  these look like some old file headers that are not used anywhere. If that is the case are we OK to remove them?

```
./src/teb/consphy.fh
./src/teb/impnone.fh
./src/teb/stabfunc2.fh
./src/teb/surfcon.fh
```

**Comment by VakankGrang** [comment]
Yes, it looks as if they were no longer used.

**Comment by dmey** [comment]
Removed in https://github.com/TEB-model/teb/commit/87a2c9a25d8d581f719f1ae9b68737d5fd6cc2c4.
